---
- name: Deploy Virtual Machine from template in content library with PowerON State
  community.vmware.vmware_content_deploy_template:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    template: '{{ vmtemplate }}'
    content_library: '{{ content_library }}'
    datastore: '{{ datastore }}'
    folder: '{{ vm_foldername }}'
    datacenter: '{{ vcenter_datacenter }}'
    name: '{{ vm_foldername }}'
    
    state: poweredon
  delegate_to: localhost
